# Generated by Django 5.0.14 on 2026-08-29 08:40

import django.contrib.postgres.fields
import django.contrib.postgres.fields.citext
import django.db.models.deletion
import django.db.models.expressions
from django.contrib.postgres.operations import CITextExtension, CryptoExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # schema_v1_1.sql opens with:
        #   CREATE EXTENSION IF NOT EXISTS citext;
        #   CREATE EXTENSION IF NOT EXISTS pgcrypto;
        # Not auto-added by makemigrations (it doesn't infer extension
        # requirements from field types) — added by hand here, first,
        # since User.email (CITextField) needs `citext` to exist before
        # its table is created. `pgcrypto` has no direct ORM-field user
        # yet, but schema_v1_1.sql enables it unconditionally, so this
        # migration matches that rather than silently dropping it.
        CITextExtension(),
        CryptoExtension(),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=80)),
                ('mobile_e164', models.CharField(max_length=15, unique=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_order_at', models.DateTimeField(blank=True, null=True)),
                ('order_count', models.IntegerField(default=0)),
                ('anonymised_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='DayDishAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('max_units', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'day_dish_availability',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.TextField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('price_cents', models.IntegerField()),
                ('portion_label', models.TextField(blank=True, null=True)),
                ('spice_default', models.TextField(blank=True, null=True)),
                ('allergen_text', models.TextField(blank=True, null=True)),
                ('dietary_tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('image_alt', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active_on_menu', models.BooleanField(default=False)),
                ('allow_notes', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dishes',
            },
        ),
        migrations.CreateModel(
            name='DishOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('required', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'dish_options',
            },
        ),
        migrations.CreateModel(
            name='DishOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price_delta_cents', models.IntegerField(default=0)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'dish_option_values',
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('key', models.TextField(primary_key=True, serialize=False)),
                ('request_sha256', models.BinaryField()),
                ('response_status', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'idempotency_keys',
            },
        ),
        migrations.CreateModel(
            name='JobHeartbeat',
            fields=[
                ('job_name', models.TextField(primary_key=True, serialize=False)),
                ('last_run_at', models.DateTimeField()),
                ('last_ok', models.BooleanField()),
                ('detail', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'job_heartbeats',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('proof', 'Proof'), ('dish_image', 'Dish image')], max_length=10)),
                ('storage_key', models.TextField(unique=True)),
                ('mime_type', models.TextField()),
                ('byte_size', models.IntegerField()),
                ('sha256', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'media',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=15, unique=True)),
                ('public_token', models.TextField(unique=True)),
                ('source', models.CharField(choices=[('website', 'Website'), ('whatsapp_assisted', 'WhatsApp (assisted)'), ('phone', 'Phone'), ('in_person', 'In person')], max_length=20)),
                ('customer_name_snapshot', models.TextField()),
                ('customer_mobile_snapshot', models.TextField()),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('awaiting_eft', 'Awaiting EFT'), ('payment_review', 'Payment review'), ('confirmed_prep', 'Confirmed (prep)'), ('cash_request', 'Cash request'), ('cash_due', 'Cash due'), ('in_kitchen', 'In kitchen'), ('ready', 'Ready'), ('collected', 'Collected'), ('payment_expired', 'Payment expired'), ('cancelled', 'Cancelled')], max_length=20)),
                ('payment_method', models.CharField(choices=[('eft', 'EFT'), ('cash', 'Cash')], max_length=10)),
                ('subtotal_cents', models.IntegerField()),
                ('discount_cents', models.IntegerField(default=0)),
                ('total_cents', models.IntegerField()),
                ('balance_due_cents', models.IntegerField(default=0)),
                ('refund_note', models.TextField(blank=True, null=True)),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('hold_extensions', models.SmallIntegerField(default=0)),
                ('dish_units_consumed', models.BooleanField(default=False)),
                ('dispute_flag', models.BooleanField(default=False)),
                ('after_cutoff_reason', models.TextField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, choices=[('customer_request', 'Customer request'), ('staff', 'Staff'), ('cash_rejected', 'Cash rejected'), ('payment_rejected', 'Payment rejected'), ('no_show', 'No-show'), ('day_closed', 'Day closed'), ('duplicate', 'Duplicate'), ('owner_exception', 'Owner exception'), ('other', 'Other')], max_length=20, null=True)),
                ('cancellation_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('in_kitchen_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('awaiting_eft', 'Awaiting EFT'), ('payment_review', 'Payment review'), ('confirmed_prep', 'Confirmed (prep)'), ('cash_request', 'Cash request'), ('cash_due', 'Cash due'), ('in_kitchen', 'In kitchen'), ('ready', 'Ready'), ('collected', 'Collected'), ('payment_expired', 'Payment expired'), ('cancelled', 'Cancelled')], max_length=20, null=True)),
                ('to_status', models.CharField(blank=True, choices=[('awaiting_eft', 'Awaiting EFT'), ('payment_review', 'Payment review'), ('confirmed_prep', 'Confirmed (prep)'), ('cash_request', 'Cash request'), ('cash_due', 'Cash due'), ('in_kitchen', 'In kitchen'), ('ready', 'Ready'), ('collected', 'Collected'), ('payment_expired', 'Payment expired'), ('cancelled', 'Cancelled')], max_length=20, null=True)),
                ('action', models.TextField()),
                ('actor_kind', models.CharField(choices=[('staff', 'Staff'), ('customer', 'Customer'), ('system', 'System')], max_length=10)),
                ('payload', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'order_events',
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name_snapshot', models.TextField()),
                ('unit_price_cents_snapshot', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('options_snapshot', models.JSONField(default=list)),
                ('option_key', models.CharField(default='', max_length=250)),
                ('line_total_cents', models.IntegerField()),
                ('kitchen_note', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'order_lines',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('eft', 'EFT'), ('cash', 'Cash')], max_length=10)),
                ('amount_cents', models.IntegerField()),
                ('reference', models.TextField()),
                ('customer_declared_ref', models.TextField(blank=True, null=True)),
                ('proof_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('collected_cash', 'Collected (cash)'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True, null=True)),
                ('cash_received_at', models.DateTimeField(blank=True, null=True)),
                ('cash_amount_received_cents', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.SmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('public_site_name', models.TextField()),
                ('collection_address_line', models.TextField(blank=True, null=True)),
                ('collection_instructions', models.TextField(blank=True, null=True)),
                ('bank_name', models.TextField(blank=True, null=True)),
                ('account_name', models.TextField(blank=True, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('branch_code', models.TextField(blank=True, null=True)),
                ('account_type', models.TextField(blank=True, null=True)),
                ('default_window_start', models.TimeField(default='16:00')),
                ('default_window_end', models.TimeField(default='18:00')),
                ('slot_minutes', models.SmallIntegerField(default=15)),
                ('default_slot_capacity', models.SmallIntegerField(default=13)),
                ('default_daily_order_cap', models.SmallIntegerField(default=100)),
                ('same_day_cutoff', models.TimeField(default='10:00')),
                ('preorder_days', models.SmallIntegerField(default=7)),
                ('eft_hold_minutes', models.SmallIntegerField(default=30)),
                ('max_hold_extensions', models.SmallIntegerField(default=1)),
                ('hold_extension_minutes', models.SmallIntegerField(default=15)),
                ('payment_review_sla_minutes', models.SmallIntegerField(default=15)),
                ('cash_enabled', models.BooleanField(default=True)),
                ('cash_same_day_only', models.BooleanField(default=True)),
                ('cash_daily_cap', models.SmallIntegerField(default=20)),
                ('collection_grace_minutes', models.SmallIntegerField(default=15)),
                ('assisted_after_cutoff_enabled', models.BooleanField(default=False)),
                ('support_whatsapp_e164', models.CharField(blank=True, max_length=16, null=True)),
                ('allergen_disclaimer', models.TextField(blank=True, null=True)),
                ('home_kitchen_notice', models.TextField(blank=True, null=True)),
                ('vat_registered', models.BooleanField(default=False)),
                ('vat_number', models.TextField(blank=True, null=True)),
                ('proof_retention_days', models.SmallIntegerField(default=90)),
                ('order_retention_months', models.SmallIntegerField(default=18)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('sms_ready_template', models.TextField(default='{site}: order {order_number} is ready. Collect {slot_label} at {address_line}. {instructions}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='SettingsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diff', models.JSONField()),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'settings_events',
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.TimeField()),
                ('end_at', models.TimeField()),
                ('capacity', models.SmallIntegerField()),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'slots',
            },
        ),
        migrations.CreateModel(
            name='ThrottleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.TextField()),
                ('key', models.TextField()),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'throttle_events',
            },
        ),
        migrations.CreateModel(
            name='TradingDay',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('is_open', models.BooleanField(default=True)),
                ('window_start', models.TimeField()),
                ('window_end', models.TimeField()),
                ('cutoff_time', models.TimeField()),
                ('daily_order_cap', models.SmallIntegerField()),
                ('next_order_seq', models.IntegerField(default=1)),
                ('kitchen_locked_at', models.DateTimeField(blank=True, null=True)),
                ('closed_out_at', models.DateTimeField(blank=True, null=True)),
                ('notes_internal', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trading_days',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', django.contrib.postgres.fields.citext.CITextField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager')], max_length=10)),
                ('password_hash', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('must_change_password', models.BooleanField(default=True)),
                ('failed_login_count', models.SmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(check=models.Q(('full_name__regex', '^.{2,80}$')), name='customers_full_name_length'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(check=models.Q(('mobile_e164__regex', '^\\+27[6-8][0-9]{8}$')), name='customers_mobile_e164_format'),
        ),
        migrations.AddField(
            model_name='daydishavailability',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_availability', to='core.dish'),
        ),
        migrations.AddField(
            model_name='dishoption',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.dish'),
        ),
        migrations.AddField(
            model_name='dishoptionvalue',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.dishoption'),
        ),
        migrations.AddField(
            model_name='media',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to='core.dish'),
        ),
        migrations.AddField(
            model_name='dish',
            name='image_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.media'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.customer'),
        ),
        migrations.AddField(
            model_name='media',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='core.order'),
        ),
        migrations.AddField(
            model_name='idempotencykey',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to='core.order'),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.order'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='core.dish'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.order'),
        ),
        migrations.AddField(
            model_name='payment',
            name='current_proof_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.media'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='core.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='core.slot'),
        ),
        migrations.AddIndex(
            model_name='throttleevent',
            index=models.Index(fields=['scope', 'key', 'occurred_at'], name='throttle_events_lookup_idx'),
        ),
        migrations.AddField(
            model_name='slot',
            name='trading_day',
            field=models.ForeignKey(db_column='trading_day', on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.tradingday'),
        ),
        migrations.AddField(
            model_name='order',
            name='trading_day',
            field=models.ForeignKey(db_column='trading_day', on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='core.tradingday'),
        ),
        migrations.AddField(
            model_name='daydishavailability',
            name='trading_day',
            field=models.ForeignKey(db_column='trading_day', on_delete=django.db.models.deletion.CASCADE, related_name='dish_availability', to='core.tradingday'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('name__regex', '^.{1,80}$')), name='users_name_length'),
        ),
        migrations.AddField(
            model_name='tradingday',
            name='closed_out_by',
            field=models.ForeignKey(blank=True, db_column='closed_out_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='tradingday',
            name='kitchen_locked_by',
            field=models.ForeignKey(blank=True, db_column='kitchen_locked_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='settingsevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='settings_events', to='core.user'),
        ),
        migrations.AddField(
            model_name='settings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='payment',
            name='cash_received_by',
            field=models.ForeignKey(blank=True, db_column='cash_received_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_by',
            field=models.ForeignKey(blank=True, db_column='verified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_events', to='core.user'),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_orders', to='core.user'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_by_user',
            field=models.ForeignKey(blank=True, help_text='Null for website orders.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_orders', to='core.user'),
        ),
        migrations.AddField(
            model_name='media',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, db_column='uploaded_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.user'),
        ),
        migrations.AddConstraint(
            model_name='dishoption',
            constraint=models.UniqueConstraint(fields=('dish', 'name'), name='dish_options_dish_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='dishoption',
            constraint=models.CheckConstraint(check=models.Q(('name__regex', '^.{1,40}$')), name='dish_options_name_length'),
        ),
        migrations.AddConstraint(
            model_name='dishoptionvalue',
            constraint=models.UniqueConstraint(fields=('option', 'name'), name='dish_option_values_option_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='dishoptionvalue',
            constraint=models.CheckConstraint(check=models.Q(('name__regex', '^.{1,40}$')), name='dish_option_values_name_length'),
        ),
        migrations.AddConstraint(
            model_name='dish',
            constraint=models.CheckConstraint(check=models.Q(('slug__regex', '^[a-z0-9]+(-[a-z0-9]+)*$')), name='dishes_slug_format'),
        ),
        migrations.AddConstraint(
            model_name='dish',
            constraint=models.CheckConstraint(check=models.Q(('name__regex', '^.{1,80}$')), name='dishes_name_length'),
        ),
        migrations.AddConstraint(
            model_name='dish',
            constraint=models.CheckConstraint(check=models.Q(('price_cents__gte', 0)), name='dishes_price_cents_non_negative'),
        ),
        migrations.AddIndex(
            model_name='idempotencykey',
            index=models.Index(fields=['created_at'], name='idempotency_keys_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(check=models.Q(('unit_price_cents_snapshot__gte', 0)), name='order_lines_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 1), ('quantity__lte', 20)), name='order_lines_quantity_range'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(check=models.Q(('line_total_cents__gte', 0)), name='order_lines_line_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(check=django.db.models.expressions.RawSQL("jsonb_typeof(options_snapshot) = 'array'", (), output_field=models.BooleanField()), name='order_lines_options_snapshot_is_array'),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('trading_day', 'start_at'), name='slots_trading_day_start_at_uniq'),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.CheckConstraint(check=models.Q(('start_at__lt', models.F('end_at'))), name='slots_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.CheckConstraint(check=models.Q(('capacity__gte', 0)), name='slots_capacity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='daydishavailability',
            constraint=models.UniqueConstraint(fields=('trading_day', 'dish'), name='day_dish_availability_pk_uniq'),
        ),
        migrations.AddConstraint(
            model_name='daydishavailability',
            constraint=models.CheckConstraint(check=models.Q(('max_units__isnull', True), ('max_units__gte', 0), _connector='OR'), name='day_dish_availability_max_units_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='tradingday',
            constraint=models.CheckConstraint(check=models.Q(('window_start__lt', models.F('window_end'))), name='trading_days_window_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='tradingday',
            constraint=models.CheckConstraint(check=models.Q(('daily_order_cap__gte', 0)), name='trading_days_daily_order_cap_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='tradingday',
            constraint=models.CheckConstraint(check=models.Q(('next_order_seq__gte', 1), ('next_order_seq__lte', 10000)), name='trading_days_next_order_seq_range'),
        ),
        migrations.AddConstraint(
            model_name='settings',
            constraint=models.CheckConstraint(check=models.Q(('id', 1)), name='settings_id_is_1'),
        ),
        migrations.AddConstraint(
            model_name='settings',
            constraint=models.CheckConstraint(check=models.Q(('account_number__isnull', True), ('account_number__regex', '^[0-9]{6,20}$'), _connector='OR'), name='settings_account_number_format'),
        ),
        migrations.AddConstraint(
            model_name='settings',
            constraint=models.CheckConstraint(check=models.Q(('slot_minutes__gte', 5), ('slot_minutes__lte', 60)), name='settings_slot_minutes_range'),
        ),
        migrations.AddConstraint(
            model_name='settings',
            constraint=models.CheckConstraint(check=models.Q(('default_slot_capacity__gte', 1)), name='settings_default_slot_capacity_min'),
        ),
        migrations.AddConstraint(
            model_name='settings',
            constraint=models.CheckConstraint(check=models.Q(('default_daily_order_cap__gte', 1)), name='settings_default_daily_order_cap_min'),
        ),
        migrations.AddConstraint(
            model_name='settings',
            constraint=models.CheckConstraint(check=models.Q(('preorder_days__gte', 0), ('preorder_days__lte', 14)), name='settings_preorder_days_range'),
        ),
        migrations.AddConstraint(
            model_name='settings',
            constraint=models.CheckConstraint(check=models.Q(('eft_hold_minutes__gte', 5), ('eft_hold_minutes__lte', 120)), name='settings_eft_hold_minutes_range'),
        ),
        migrations.AddConstraint(
            model_name='settings',
            constraint=models.CheckConstraint(check=models.Q(('max_hold_extensions__gte', 0), ('max_hold_extensions__lte', 3)), name='settings_max_hold_extensions_range'),
        ),
        migrations.AddConstraint(
            model_name='settings',
            constraint=models.CheckConstraint(check=models.Q(('hold_extension_minutes__gte', 5), ('hold_extension_minutes__lte', 60)), name='settings_hold_extension_minutes_range'),
        ),
        migrations.AddConstraint(
            model_name='settings',
            constraint=models.CheckConstraint(check=models.Q(('payment_review_sla_minutes__gte', 5), ('payment_review_sla_minutes__lte', 120)), name='settings_payment_review_sla_minutes_range'),
        ),
        migrations.AddConstraint(
            model_name='settings',
            constraint=models.CheckConstraint(check=models.Q(('cash_daily_cap__gte', 0)), name='settings_cash_daily_cap_min'),
        ),
        migrations.AddConstraint(
            model_name='settings',
            constraint=models.CheckConstraint(check=models.Q(('collection_grace_minutes__gte', 0), ('collection_grace_minutes__lte', 60)), name='settings_collection_grace_minutes_range'),
        ),
        migrations.AddConstraint(
            model_name='settings',
            constraint=models.CheckConstraint(check=models.Q(('support_whatsapp_e164__isnull', True), ('support_whatsapp_e164__regex', '^\\+[1-9][0-9]{7,14}$'), _connector='OR'), name='settings_support_whatsapp_format'),
        ),
        migrations.AddConstraint(
            model_name='settings',
            constraint=models.CheckConstraint(check=models.Q(('proof_retention_days__gte', 30), ('proof_retention_days__lte', 365)), name='settings_proof_retention_days_range'),
        ),
        migrations.AddConstraint(
            model_name='settings',
            constraint=models.CheckConstraint(check=models.Q(('order_retention_months__gte', 6), ('order_retention_months__lte', 60)), name='settings_order_retention_months_range'),
        ),
        migrations.AddConstraint(
            model_name='settings',
            constraint=models.CheckConstraint(check=models.Q(('default_window_start__lt', models.F('default_window_end'))), name='settings_window_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='settings',
            constraint=models.CheckConstraint(check=models.Q(('same_day_cutoff__lt', models.F('default_window_start'))), name='settings_cutoff_before_window_start'),
        ),
        migrations.AddConstraint(
            model_name='settings',
            constraint=models.CheckConstraint(check=models.Q(('cash_daily_cap__lte', models.F('default_daily_order_cap'))), name='settings_cash_cap_le_daily_cap'),
        ),
        migrations.AddConstraint(
            model_name='settings',
            constraint=models.CheckConstraint(check=models.Q(('vat_registered', False), ('vat_number__isnull', False), _connector='OR'), name='settings_vat_number_required_if_registered'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(('amount_cents__gte', 0)), name='payments_amount_cents_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(('cash_amount_received_cents__isnull', True), ('cash_amount_received_cents__gte', 0), _connector='OR'), name='payments_cash_amount_received_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'verified'), _negated=True), models.Q(('verified_by__isnull', False), ('verified_at__isnull', False)), _connector='OR'), name='payments_verified_requires_verifier_and_time'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'collected_cash'), _negated=True), models.Q(('cash_received_by__isnull', False), ('cash_received_at__isnull', False), ('cash_amount_received_cents__isnull', False)), _connector='OR'), name='payments_collected_cash_requires_receipt_fields'),
        ),
        migrations.AddIndex(
            model_name='orderevent',
            index=models.Index(fields=['order', 'occurred_at'], name='order_events_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('actor_kind', 'staff'), _negated=True), ('actor_user__isnull', False), _connector='OR'), name='order_events_staff_requires_actor_user'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['trading_day', 'status'], name='orders_day_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['slot', 'status'], name='orders_slot_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('status', 'awaiting_eft')), fields=['hold_expires_at'], name='orders_hold_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_mobile_snapshot'], name='orders_mobile_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('total_cents', django.db.models.expressions.CombinedExpression(models.F('subtotal_cents'), '-', models.F('discount_cents')))), name='orders_total_equals_subtotal_minus_discount'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'cancelled'), _negated=True), ('cancellation_reason__isnull', False), _connector='OR'), name='orders_cancelled_requires_reason'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'awaiting_eft'), _negated=True), ('hold_expires_at__isnull', False), _connector='OR'), name='orders_awaiting_eft_requires_hold_expiry'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('payment_method', 'eft'), ('hold_expires_at__isnull', True), _connector='OR'), name='orders_hold_expiry_only_for_eft'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('dish_units_consumed', False), ('in_kitchen_at__isnull', False), _connector='OR'), name='orders_dish_units_consumed_requires_in_kitchen_at'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('subtotal_cents__gte', 0)), name='orders_subtotal_cents_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('discount_cents__gte', 0)), name='orders_discount_cents_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('total_cents__gte', 0)), name='orders_total_cents_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('balance_due_cents__gte', 0)), name='orders_balance_due_cents_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('hold_extensions__gte', 0)), name='orders_hold_extensions_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('order_number__regex', '^CT-[0-9]{6}-[0-9]{4}$')), name='orders_order_number_format'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('public_token__regex', '^.{22,}$')), name='orders_public_token_min_length'),
        ),
        migrations.AddConstraint(
            model_name='media',
            constraint=models.CheckConstraint(check=models.Q(('byte_size__gt', 0), ('byte_size__lte', 8388608)), name='media_byte_size_range'),
        ),
        migrations.AddConstraint(
            model_name='media',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('kind', 'proof'), _negated=True), ('mime_type__in', ['image/jpeg', 'image/png', 'image/webp', 'application/pdf']), _connector='OR'), name='media_proof_mime_type'),
        ),
        migrations.AddConstraint(
            model_name='media',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('kind', 'dish_image'), _negated=True), ('mime_type__in', ['image/jpeg', 'image/png', 'image/webp']), _connector='OR'), name='media_dish_image_mime_type'),
        ),
    ]
