# Generated by Django 5.0.14 on 2026-09-15 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_google_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to='core.user')),
            ],
            options={
                'db_table': 'device_tokens',
                'indexes': [models.Index(fields=['staff_user'], name='device_tokens_staff_user_idx')],
            },
        ),
    ]
